name: 'Annotate Image Tags'
description: 'Finds all tags for a digest and applies OCI annotations'
inputs:
  registry:
    description: 'Registry URL (e.g., ghcr.io/)'
    required: true
  image_name:
    description: 'Image name/path'
    required: true
  tag_or_digest:
    description: 'Target tag (:latest) or digest (@sha256:...)'
    required: true
  description:
    description: 'The description annotation value'
    required: true
  scan_outcome:
    description: 'The outcome of the security scan'
    required: true
  github_token:
    description: 'GITHUB_TOKEN with package write access'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # 1. Populate tags list to update
        update_tags=()
        update_tags+=("-t ${{ inputs.registry }}${{ inputs.image_name }}:latest")
        
        # 2. Create the new manifest
        docker buildx imagetools create \
          "${update_tags[@]}" \
          --annotation "index:org.opencontainers.image.description=${{ inputs.description }} (Trivy scan - ${{ inputs.scan_outcome }})" \
          --annotation "index:compliance.trivy.status=${{ inputs.scan_outcome }}" \
          --annotation "index:compliance.trivy.timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          "${{ inputs.registry }}${{ inputs.image_name }}${{ inputs.tag_or_digest }}"
