/*------------------------------------------------------------------------*
 * Copyright (c) 2026 Sonu Sonkar.                                        *
 * Licensed under the MIT License.                                        *
 * See the LICENSE file in the project root for full license information. *
 *------------------------------------------------------------------------*/
syntax = "proto3";

package sustainability;

service NTNService {
  rpc ComputeState (NTNRequest) returns (NTNResponse);
}

message NTNRequest {
  int32 current_state = 1;
  int32 critical_count = 2;
  int32 recovery_count = 3;
  float score = 4;
}

message NTNResponse {
  int32 new_state = 1;
  int32 new_critical_count = 2;
  int32 new_recovery_count = 3;
}
