/*------------------------------------------------------------------------*
 * Copyright (c) 2026 Sonu Sonkar.                                        *
 * Licensed under the MIT License.                                        *
 * See the LICENSE file in the project root for full license information. *
 *------------------------------------------------------------------------*/
syntax = "proto3";

package sustainability;

message VoidMsg {}

service SustainerService {
  // Forces the worker to reload its sliding window from DB
  rpc ResetHydration (VoidMsg) returns (SustainerStatus);
}

message SustainerStatus { bool success = 1; string message = 2; }
