name: Build
# Build the images

run-name: >-
  ${{ github.workflow }}: 
  ${{ github.event_name }} 
  - # ${{ github.run_number }}
  - at ${{ github.run_attempt }}
  - sha [${{ github.event.workflow_run.head_sha || github.sha }}]

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger
    inputs:
      info:
        description: '⚠️ Force a full build of both images.'
        required: false
        type: choice
        options:
          - "Full build"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REGISTRY: ghcr.io/${{ github.repository_owner }}/
  # Converts repository name to lowercase for GHCR compatibility
  IMAGE_NAME_GRPC: ntn-sustainability-control-grpc
  IMAGE_NAME_WEB: ntn-sustainability-control-web

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@v6

      # Detect which folders changed
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            grpc: ['grpc/**']
            web: ['web/**']
      
      - name: Set environment vars
        id: vars
        run: |
          # Local vars
          tag=$(git rev-parse --short HEAD)
          bld_num=${{ github.run_number }}
          bld_dt=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          
          g_ver="v2.0.1"
          g_bld_msg="Gold_Chainguard"
          g_full_ver="$g_ver-$tag-$bld_num-$g_bld_msg"
          
          w_ver="v2.0.3"
          w_bld_msg="Gold_Chainguard"
          w_full_ver="$w_ver-$tag-$bld_num-$w_bld_msg"

          # Env vars
          echo "IMAGE_TAG=$tag" >> $GITHUB_ENV
          echo "BLD_NMBR=$bld_num" >> $GITHUB_ENV
          echo "BLD_DATE=$bld_dt" >> $GITHUB_ENV
          
          echo "GRPC_VER=$g_ver" >> $GITHUB_ENV
          echo "GRPC_BLD_MSG=$g_bld_msg" >> $GITHUB_ENV
          echo "GRPC_FULL_VER=$g_full_ver" >> $GITHUB_ENV
          
          echo "WEB_VER=$w_ver" >> $GITHUB_ENV
          echo "WEB_BLD_MSG=$w_bld_msg" >> $GITHUB_ENV
          echo "WEB_FULL_VER=$w_full_ver" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: |
          steps.changes.outputs.grpc == 'true' || steps.changes.outputs.web == 'true' ||
          github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v4

      # --- gRPC Build (with trivy scan label), and Save ---
      - name: Build (with trivy scan label) and Save gRPC Image
        if: |
          steps.changes.outputs.grpc == 'true' || github.event_name == 'workflow_dispatch'
        id: build-grpc
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./grpc/Dockerfile
          tags: |
            ${{ env.REGISTRY }}${{ env.IMAGE_NAME_GRPC }}:latest
          labels: |
            org.opencontainers.image.description=Multiple gRPC services to monitor and maintain 6G sustainability KPIs. [Version: ${{ env.GRPC_FULL_VER }}] [Trivy Scan: (No critical or high vulnerabilities)] [Build Date: ${{ env.BLD_DATE }}]
          build-args: |
            GRPC_VER=${{ env.GRPC_VER }}
            IMAGE_TAG=${{ env.IMAGE_TAG }}
            GRPC_BLD_MSG=${{ env.GRPC_BLD_MSG }}
            BLD_NMBR=${{ env.BLD_NMBR }}
          outputs: type=docker, dest=./tmp/grpc-image.tar

      # --- Web Build (with trivy scan label), and Save ---
      - name: Build (with trivy scan label) and Save Web Image
        if: |
          steps.changes.outputs.web == 'true' || github.event_name == 'workflow_dispatch'
        id: build-web
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./web/Dockerfile
          tags: |
            ${{ env.REGISTRY }}${{ env.IMAGE_NAME_WEB }}:latest
          labels: |
            org.opencontainers.image.description=NTN Sustainability Control - Web GUI [Version: ${{ env.WEB_FULL_VER }}] [Trivy Scan: (No critical or high vulnerabilities)] [Build Date: ${{ env.BLD_DATE }}]
          build-args: |
            WEB_VER=${{ env.WEB_VER }}
            IMAGE_TAG=${{ env.IMAGE_TAG }}
            WEB_BLD_MSG=${{ env.WEB_BLD_MSG }}
            BLD_NMBR=${{ env.BLD_NMBR }}
          outputs: type=docker, dest=./tmp/web-image.tar

      - name: Upload Images
        if: steps.build-grpc.outcome == 'success' || steps.build-web.outcome == 'success'
        uses: actions/upload-artifact@v6
        with:
          name: upload-images
          path: ./tmp/*-image.tar
          # Optional: Keep it for a short time to save storage
          retention-days: 1

      # --- Show summary ---
      - name: Summary Status
        if: always()
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          ---
          ### Build Status Summary
          ---
          | **Image** | **Status** | **Version** |
          |:---------:|:----------:|:-----------:|
          | gRPC      | ${{ steps.build-grpc.outcome == 'success' && '✅ Passed' || (steps.build-grpc.outcome == 'skipped' && '⚪ Skipped' || '❌ Failed') }} | ${{ steps.build-grpc.outcome == 'skipped' && '➖' || env.GRPC_FULL_VER }} |
          | Web       | ${{ steps.build-web.outcome == 'success' && '✅ Passed' || (steps.build-web.outcome == 'skipped' && '⚪ Skipped' || '❌ Failed') }} | ${{ steps.build-web.outcome == 'skipped' && '➖' || env.WEB_FULL_VER }} |
          ---
          EOF

      # Update common status
      - name: Update Unified Pipeline Status
        if: always()
        run: |
          # Use the head_sha from the trigger or the current sha
          SHA=${{ github.event.workflow_run.head_sha || github.sha }}

          if [[ "${{ steps.build-grpc.outcome }}" == "skipped" && "${{ steps.build-web.outcome }}" == "skipped" ]]; then
            desc="Skipped"
          else
            desc="${{ job.status == 'success' && 'Successful' || 'Failed' }}"
          fi

          gh api repos/${{ github.repository }}/statuses/$SHA \
            -f state="${{ job.status == 'success' && 'success' || 'failure' }}" \
            -f context="${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})" \
            -f description="$desc" \
            -f target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
